on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Instala o node com a versão
        uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Instala dependências
        run: npm i
      - name: Roda eslint
        run: npx eslint